blank_issues_enabled: false
contact_links:
  - name: Decentra Network Community Support
    url: https://github.com/Decentra-Network/Decentra-Network/discussions
    about: Please ask and answer questions here.
